version: '3.8'

services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: crud
    build: .
    
    volumes:
      - .:/code
    ports:
      - 8008:8000
    depends_on:
      - migration_app

    command: python main.py

  migration_app:
    container_name: migration_app
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    command: bash -c "alembic revision --autogenerate && alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
  
volumes:
  postgres_data: